export default {
  ACCOUNT_FETCH_LIST: 'ACCOUNT_FETCH_LIST',
  ACCOUNT_REPLACE_ACCOUNT: 'ACCOUNT_REPLACE_ACCOUNT',

  ACCOUNT_DETAIL_FETCH: 'ACCOUNT_DETAIL_FETCH',
  ACCOUNT_DETAIL_TAP_DELETE: 'ACCOUNT_DETAIL_TAP_DELETE',
  ACCOUNT_DETAIL_UNMOUNT: 'ACCOUNT_DETAIL_UNMOUNT',

  ACCOUNT_ADD_FETCH: 'ACCOUNT_ADD_FETCH',
  ACCOUNT_ADD_CHANGE_NAME: 'ACCOUNT_ADD_CHANGE_NAME',
  ACCOUNT_ADD_CHANGE_MEMBER_EMAIL: 'ACCOUNT_ADD_CHANGE_MEMBER_EMAIL',
  ACCOUNT_ADD_TOGGLE_SHARE: 'ACCOUNT_ADD_TOGGLE_SHARE',
  ACCOUNT_ADD_ADD_MEMBER: 'ACCOUNT_ADD_ADD_MEMBER',
  ACCOUNT_ADD_TAP_SAVE: 'ACCOUNT_ADD_TAP_SAVE',
  ACCOUNT_ADD_UNMOUNT: 'ACCOUNT_ADD_UNMOUNT',

  COUCHDB_TAP_IMPORT: 'COUCHDB_TAP_IMPORT',
  COUCHDB_TAP_IMPORT_START: 'COUCHDB_TAP_IMPORT_START',
  COUCHDB_TAP_IMPORTED: 'COUCHDB_TAP_IMPORTED',
  COUCHDB_TAP_EXPORT: 'COUCHDB_TAP_EXPORT',
  COUCHDB_TAP_EXPORTED: 'COUCHDB_TAP_EXPORTED',
  COUCHDB_FETCH_USER: 'COUCHDB_FETCH_USER',

  EXPENSE_ADD_FETCH: 'EXPENSE_ADD_FETCH',
  EXPENSE_ADD_TAP_SAVE: 'EXPENSE_ADD_TAP_SAVE',
  EXPENSE_ADD_CHANGE_PAID_BY: 'EXPENSE_ADD_CHANGE_PAID_BY',
  EXPENSE_ADD_CHANGE_RELATED_ACCOUNT: 'EXPENSE_ADD_CHANGE_RELATED_ACCOUNT',
  EXPENSE_ADD_CHANGE_CURRENT: 'EXPENSE_ADD_CHANGE_CURRENT',
  EXPENSE_ADD_CHANGE_PAID_FOR: 'EXPENSE_ADD_CHANGE_PAID_FOR',
  EXPENSE_ADD_ADD_MEMBER: 'EXPENSE_ADD_ADD_MEMBER',
  EXPENSE_ADD_TAP_DELETE: 'EXPENSE_ADD_TAP_DELETE',
  EXPENSE_ADD_UNMOUNT: 'EXPENSE_ADD_UNMOUNT',

  FACEBOOK_LOGIN: 'FACEBOOK_LOGIN',
  FACEBOOK_UPDATE_LOGIN_STATUS: 'FACEBOOK_UPDATE_LOGIN_STATUS',
  FACEBOOK_UPDATE_ME_INFO: 'FACEBOOK_UPDATE_ME_INFO',

  MODAL_UPDATE: 'MODAL_UPDATE',
  MODAL_DISMISS: 'MODAL_DISMISS',

  SCREEN_SHOW_DIALOG: 'SCREEN_SHOW_DIALOG',
  SCREEN_DISMISS_DIALOG: 'SCREEN_DISMISS_DIALOG',

  SNACKBAR_SHOW: 'SNACKBAR_SHOW',
  SNACKBAR_DISMISS: 'SNACKBAR_DISMISS',
};
