'use strict';

module.exports = {
  ACCOUNT_FETCH_ALL: 'ACCOUNT_FETCH_ALL',
  ACCOUNT_REPLACE_ACCOUNT: 'ACCOUNT_REPLACE_ACCOUNT',
  ACCOUNT_TAP_LIST: 'ACCOUNT_TAP_LIST',
  ACCOUNT_TAP_ADD_EXPENSE: 'ACCOUNT_TAP_ADD_EXPENSE',
  ACCOUNT_TAP_ADD_EXPENSE_FOR_ACCOUNT: 'ACCOUNT_TAP_ADD_EXPENSE_FOR_ACCOUNT',
  ACCOUNT_TAP_ADD_ACCOUNT: 'ACCOUNT_TAP_ADD_ACCOUNT',
  ACCOUNT_TAP_SETTINGS: 'ACCOUNT_TAP_SETTINGS',
  ACCOUNT_DELETE_CURRENT: 'ACCOUNT_DELETE_CURRENT',
  ACCOUNT_NAVIGATE_HOME: 'ACCOUNT_NAVIGATE_HOME',

  ACCOUNT_ADD_CLOSE: 'ACCOUNT_ADD_CLOSE',
  ACCOUNT_ADD_CHANGE_NAME: 'ACCOUNT_ADD_CHANGE_NAME',
  ACCOUNT_ADD_CHANGE_MEMBER_EMAIL: 'ACCOUNT_ADD_CHANGE_MEMBER_EMAIL',
  ACCOUNT_ADD_TOGGLE_SHARE: 'ACCOUNT_ADD_TOGGLE_SHARE',
  ACCOUNT_ADD_TAP_SAVE: 'ACCOUNT_ADD_TAP_SAVE',

  COUCHDB_TAP_IMPORT: 'COUCHDB_TAP_IMPORT',
  COUCHDB_TAP_IMPORT_START: 'COUCHDB_TAP_IMPORT_START',
  COUCHDB_TAP_IMPORTED: 'COUCHDB_TAP_IMPORTED',
  COUCHDB_TAP_EXPORT: 'COUCHDB_TAP_EXPORT',
  COUCHDB_TAP_EXPORTED: 'COUCHDB_TAP_EXPORTED',
  COUCHDB_FETCH_USER: 'COUCHDB_FETCH_USER',

  EXPENSE_CLOSE: 'EXPENSE_CLOSE',
  EXPENSE_TAP_SAVE: 'EXPENSE_TAP_SAVE',
  EXPENSE_TAP_SAVED: 'EXPENSE_TAP_SAVED',
  EXPENSE_TAP_LIST: 'EXPENSE_TAP_LIST',
  EXPENSE_CHANGE_PAID_BY: 'EXPENSE_CHANGE_PAID_BY',
  EXPENSE_CHANGE_RELATED_ACCOUNT: 'EXPENSE_CHANGE_RELATED_ACCOUNT',
  EXPENSE_CHANGE_CURRENT: 'EXPENSE_CHANGE_CURRENT',
  EXPENSE_PICK_CONTACT: 'EXPENSE_PICK_CONTACT',
  EXPENSE_DELETE_CURRENT: 'EXPENSE_DELETE_CURRENT',

  FACEBOOK_LOGIN: 'FACEBOOK_LOGIN',
  FACEBOOK_UPDATE_LOGIN_STATUS: 'FACEBOOK_UPDATE_LOGIN_STATUS',
  FACEBOOK_UPDATE_ME_INFO: 'FACEBOOK_UPDATE_ME_INFO',

  MODAL_UPDATE: 'MODAL_UPDATE',
  MODAL_DISMISS: 'MODAL_DISMISS',

  SCREEN_NAVIGATE_TO: 'SCREEN_NAVIGATE_TO',
  SCREEN_SHOW_DIALOG: 'SCREEN_SHOW_DIALOG',
  SCREEN_DISMISS_DIALOG: 'SCREEN_DISMISS_DIALOG',

  SNACKBAR_SHOW: 'SNACKBAR_SHOW',
  SNACKBAR_DISMISS: 'SNACKBAR_DISMISS',
};
