'use strict';

const selector = {
  mainActionButton: '.testMainActionButton',
  expenseAddSave: '.testExpenseSave',
  expenseAddDescription: '.testExpenseAddDescription input',
  expenseAddAmount: '.testExpenseAddAmount input',
  expenseAddCurrency: '.testExpenseAddCurrency',
  expenseAddRelatedAccount: '.testExpenseAddRelatedAccount',
  expenseAddRelatedAccountDialog: '.testExpenseAddRelatedAccountDialog',
  expenseAddPaidFor: '.testExpenseAddPaidFor',
  expenseAddPaidBy: '.testExpenseAddPaidBy',
  expenseAddPaidByDialog: '.testExpenseAddPaidByDialog',
  expenseAddPaidByDialogIcon: '.testExpenseAddPaidByDialogIcon',
  bottomButton: '.testBottomButton',
  modal: '.testModal',
  listItem: '.testListItem',
  listItemBody: '.testListItemBody',
  listItemBodyRight: '.testListItemBodyRight',
  listSubheader: '.testListSubheader',
  appBarLeftButton: '.testAppBar button',
  appBarTitle: '.testAppBar h1',
  appBarTab: '.testAppBar > div > div:nth-child(1)',
  accountBalanceChart: '.testAccountBalanceChart',
  accountTransfer: '.testAccountTransfer',
  accountTransferValue: '.testAccountTransfer div:nth-child(2)',
  accountMore: '.testAccountMore',
  accountEditSetting: '.testAccountEditSetting',
  accountEditDelete: '.testAccountEditDelete',
  accountEditSave: '.testAccountEditSave',
  accountEditName: '.testAccountEditName input',
  settings: '.testSettings',
  settingsExport: '.testSettingsExport',
  settingsExportTextarea: '#testSettingsExportTextarea',
  settingsExportDialog: '.testSettingsExportDialog',
  settingsImport: '.testSettingsImport',
  settingsImportTextarea: '#testSettingsImportTextarea',
  settingsImportDialog: '.testSettingsImportDialog',
  snackbar: '.testSnackbar',
};

module.exports = selector;
